<?php

namespace Acme\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        require_once '/opt/lampp/htdocs/symblog/app/cache/dev/jms_diextra/proxies/Acme-BlogBundle-Controller-BlogController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Acme\\BlogBundle\\Controller\\BlogController' => array('newAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_c7b864ff3a0a19b035af6dad9e233c12d3af5290\__CG__\Acme\BlogBundle\Controller\BlogController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
